/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_arraylists;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author SKX Kafei
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnCensurar = new javax.swing.JButton();
        BtnInterseccion = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnOpcion1 = new javax.swing.JButton();
        BtnOpcion2 = new javax.swing.JButton();
        BtnOpcion3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Proyecto Grupal ArrayLists");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BtnCensurar.setBackground(new java.awt.Color(153, 153, 153));
        BtnCensurar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCensurar.setText("Censurar ");
        BtnCensurar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCensurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCensurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCensurarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCensurarMouseExited(evt);
            }
        });
        BtnCensurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCensurarActionPerformed(evt);
            }
        });

        BtnInterseccion.setBackground(new java.awt.Color(153, 153, 153));
        BtnInterseccion.setForeground(new java.awt.Color(255, 255, 255));
        BtnInterseccion.setText("Interseccion");
        BtnInterseccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnInterseccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnInterseccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnInterseccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnInterseccionMouseExited(evt);
            }
        });
        BtnInterseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInterseccionActionPerformed(evt);
            }
        });

        BtnSalir.setBackground(new java.awt.Color(255, 255, 255));
        BtnSalir.setForeground(new java.awt.Color(255, 51, 51));
        BtnSalir.setText("Salir");
        BtnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_arraylists/programacion.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_arraylists/programacion.png"))); // NOI18N

        BtnOpcion1.setBackground(new java.awt.Color(153, 153, 153));
        BtnOpcion1.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpcion1.setText("Opcion 1");
        BtnOpcion1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnOpcion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnOpcion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnOpcion1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnOpcion1MouseExited(evt);
            }
        });
        BtnOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpcion1ActionPerformed(evt);
            }
        });

        BtnOpcion2.setBackground(new java.awt.Color(153, 153, 153));
        BtnOpcion2.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpcion2.setText("Opcion 2");
        BtnOpcion2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnOpcion2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnOpcion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnOpcion2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnOpcion2MouseExited(evt);
            }
        });
        BtnOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpcion2ActionPerformed(evt);
            }
        });

        BtnOpcion3.setBackground(new java.awt.Color(153, 153, 153));
        BtnOpcion3.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpcion3.setText("Opcion 3");
        BtnOpcion3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnOpcion3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnOpcion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnOpcion3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnOpcion3MouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_arraylists/java.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BtnOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnCensurar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnInterseccion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnOpcion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnOpcion3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnInterseccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(BtnCensurar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnOpcion2ActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        BtnSalir.setBackground(Color.red);
        BtnSalir.setForeground(Color.white);
        JOptionPane.showMessageDialog(null, "Saliendo del programa...");
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnInterseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInterseccionActionPerformed
        String StrConj1 = JOptionPane.showInputDialog(null, "Ingrese el tamaño del primer conjunto: ");
        int s1 = Integer.parseInt(StrConj1);
        String StrConj2 = JOptionPane.showInputDialog(null, "Ingrese el tamaño del segundo conjunto: ");
        int s2 = Integer.parseInt(StrConj2);

        ArrayList<Character> a = fillArray(s1, 25, 97);
        ArrayList<Character> b = fillArray(s2, 25, 97);
        ArrayList<Character> c = interseccion(a, b);

        JOptionPane.showMessageDialog(null, "ArrayList No. 1:\n" + a);
        JOptionPane.showMessageDialog(null, "ArrayList No. 2:\n" + b);
        JOptionPane.showMessageDialog(null, "Interseccion:\n" + c);
    }//GEN-LAST:event_BtnInterseccionActionPerformed

    private void BtnInterseccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnInterseccionMouseExited
        BtnInterseccion.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnInterseccionMouseExited

    private void BtnInterseccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnInterseccionMouseEntered
        BtnInterseccion.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnInterseccionMouseEntered

    private void BtnCensurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCensurarActionPerformed

        String[] tokenizedMessage;

        ArrayList<String> bannedWords = addBannedWords();

        String mensaje = JOptionPane.showInputDialog(null, "Ingrese el mensaje que desea enviar: ");

        tokenizedMessage = mensaje.split(" ");
        JOptionPane.showMessageDialog(null, printMessage(censoredMessage(bannedWords, tokenizedMessage)));
    }//GEN-LAST:event_BtnCensurarActionPerformed

    private void BtnCensurarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCensurarMouseExited
        BtnCensurar.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnCensurarMouseExited

    private void BtnCensurarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCensurarMouseEntered
        BtnCensurar.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnCensurarMouseEntered

    private void BtnOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpcion1ActionPerformed
      
    }//GEN-LAST:event_BtnOpcion1ActionPerformed

    private void BtnOpcion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnOpcion1MouseEntered
       BtnOpcion1.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnOpcion1MouseEntered

    private void BtnOpcion2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnOpcion2MouseEntered
       BtnOpcion2.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnOpcion2MouseEntered

    private void BtnOpcion3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnOpcion3MouseEntered
         BtnOpcion3.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnOpcion3MouseEntered

    private void BtnOpcion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnOpcion1MouseExited
        BtnOpcion1.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnOpcion1MouseExited

    private void BtnOpcion2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnOpcion2MouseExited
        BtnOpcion2.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnOpcion2MouseExited

    private void BtnOpcion3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnOpcion3MouseExited
        BtnOpcion3.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnOpcion3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    public static ArrayList<Character> fillArray(int size, int range, int start) {
        Random rand = new Random();
        ArrayList<Character> list = new ArrayList<>();

        for (int i = 0; i < size; i++) {
            list.add((char) (start + rand.nextInt(range)));
        }
        return list;
    }

    public static ArrayList<Character> interseccion(ArrayList<Character> a, ArrayList<Character> b) {
        ArrayList<Character> intersection = new ArrayList<>();

        if (a.size() > b.size()) {
            for (int i = 0; i < b.size(); i++) {
                //Si la lista a contiene el i-esimo elemento de la lista b haga...
                //Si la lista mas grande contiene el i-esimo elemento de la lista pequeña Y la lista de interseccion NO contiene el elemento i-esimo de la lista pequeña agregue
                if (a.contains(b.get(i)) && !intersection.contains(b.get(i))) {
                    intersection.add(b.get(i));
                }
            }
        } else {
            //for each
            //Declaracion for (Tipo_de_dato nombre_de_variable_a_utilizar : nombre_de_la_coleccion_a_recorrer)

            //En el foreach, cuando accesamos nombre_de_variable_a_utilizar es como que en cada iteracion se haga lo siguiente:
            //Tipo_de_dato nombre_de_variable_a_utilizar = nombre_de_la_coleccion_a_recorrer.get(i);
            for (Character character : a) {
                if (b.contains(character) && !intersection.contains(character)) {
                    intersection.add(character);
                }
            }
        }
        return intersection;
    }

    public static ArrayList<String> addBannedWords() {
        char resp = 'n';
       

        ArrayList<String> bannedWords = new ArrayList<>();

        do {
            String cadena = JOptionPane.showInputDialog(null, "Ingrese una palabra que desea censurar: ");
            //nextLine() sin asignarselo a nada es necesario siempre que antes de leer una cadena se leyo cualquier otro tipo de dato
            bannedWords.add(cadena);
            String respuesta = JOptionPane.showInputDialog(null, "Desea agregar otra palabra? [s/n]: ");
            resp = respuesta.charAt(0);
            
        } while (resp != 'n' && resp != 'N');

        return bannedWords;
    }

    public static ArrayList<String> censoredMessage(ArrayList<String> bannedWords, String[] tokens) {
        ArrayList<String> censoredMessage = new ArrayList<>();
        for (int i = 0; i < tokens.length; i++) {
            if (bannedWords.contains(tokens[i])) {
                censoredMessage.add(censoredWord(tokens[i]));
            } else {
                censoredMessage.add(tokens[i]);
            }
        }
        return censoredMessage;
    }

    public static String censoredWord(String word) {
        String censoredWord = "";
        for (int i = 0; i < word.length(); i++) {
            censoredWord += "*";
        }
        return censoredWord;
    }

    public static String printMessage(ArrayList<String> message) {
        String msg = "";
        for (String string : message) {
            msg += string + ' ';
        }
        return msg;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCensurar;
    private javax.swing.JButton BtnInterseccion;
    private javax.swing.JButton BtnOpcion1;
    private javax.swing.JButton BtnOpcion2;
    private javax.swing.JButton BtnOpcion3;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
